### ISSUE TITLE
关于READ MORE

### ISSUE THREAD

**Issue by ECHANEEZYY** [hpcslag/hexo-theme-morgan#3]
请问READ MORE 怎么使用 < ! - - m o r e - - > 方法断开文章而不是用限制字符的方式呢？

**Comment by hpcslag** [comment]
Hi, 我目前只有以字符數量作為段開文章方式，我這幾天更新再把  的功能再加上去!

**Comment by ECHANEEZYY** [comment]
Thanks!! 酷！很喜欢你的主题😁

**Comment by hpcslag** [comment]
已經加入支持 Hexo 原生  的功能:

![](https://i.imgur.com/ykgE3Zw.png)

更新前記得備份一下 theme 裡面的 _config.yml.
