### ISSUE TITLE
the publish time of blog is not the same as true time

### ISSUE THREAD

**Issue by yelublue** [hpcslag/hexo-theme-morgan#4]
![image](https://user-images.githubusercontent.com/41419025/61921204-e2fda000-af8e-11e9-9b1d-ac5313501d68.png)

pulish time is may

true time is june

how to fix it?

**Comment by hpcslag** [comment]
Thank you for report this. 

In Javascript, `new Date().getMonth()` is start from 0, so it shows the results of last month.

I have update the theme, please refer this instruction to update your theme: [Hexo Theme Morgen - Update](https://github.com/hpcslag/hexo-theme-morgan#update)

Reference: 
[StackOverflow - getMonth in javascript gives last month](https://stackoverflow.com/questions/18624326/getmonth-in-javascript-gives-last-month)
